[build]
  command = "npm run build"
  publish = "dist"

[template.environment]
  VUE_APP_API_HOST = "This is host of your backend server"
  VUE_APP_API_KEY = "Please specific backend api key"
  VUE_APP_API_VERSION = "v1"